[input]
prepend_keymap = [
  { on = "<Esc>", run = [ "close", "mgr:escape --filter" ], desc = "Close and cancel filter" },
]

[mgr]
prepend_keymap = [
    { on = "<Up>", run = "arrow -1", description = "Previous task" },
    { on = "<Down>", run = "arrow 1", description = "Next task" },
    { on = "k", run = "arrow -1", description = "Previous task" },
    { on = "j", run = "arrow 1", description = "Next task" },
    { on = "<Space>", run = [ "toggle", "arrow 1" ], desc = "Toggle the current selection state" },
    { on = "r",         run = "bulk_rename",  desc = "Rename selected file(s) in editor" },
    { on = "<Tab>", run = "shell --block 'preview --full --no-color -- %s | nvim -M -n -c \"set buftype=nofile shortmess+=I\" -'", desc = "Preview with nvim" },
    { on = "e", run = "shell --block '${EDITOR:-vi} %s'", desc = "Edit with $EDITOR" },
]
