[mgr]
show_hidden = true
show_symlink = false

[tasks]
suppress_preload = true
macro_workers = 1
micro_workers = 1
#image_bound = [20000, 20000]

[preview]
wrap = "no"
#max_width = 1200
#max_height = 1800

[plugin]
# too slow - especially on network mounts
# this can also result in processes lingering after exit
fetchers = [
	{ id = "mime", url = "*/", run = "mime.dir", prio = "high" },
	{ id = "mime", url = "*", run = "dummy-mime", prio = "high" },
]
preloaders = []
previewers = [
	{ url = "*/", run = "folder" },
#    { mime = "image/*", run = "image-preview" },
    { url = "*", run = 'piper -- preview "$1"' },
]
#prepend_previewers = [
#    { mime = "audio/*", run = "audio-preview" },
#    { mime = "image/*", run = "image-preview" },
#    { mime = "video/*", run = "video-preview" },
#]
